spring:
  application:
    name: bjj-metrics
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:900000}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN:2592000000}
      recovery-password-token:
        expiration: ${JWT_RECOVERY_TOKEN:600000}

app-client:
  feignUrl: http://localhost:8080

notification-client:
  feignUrl: http://localhost:8080
