spring:
  application:
    name: bjj-metrics
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:3600000}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN:7200000}

app-client:
  feignUrl: http://localhost:8080

notification-client:
  feignUrl: http://localhost:8080